# Generated by Django 5.0.2 on 2024-02-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
